-- Insert bulk products with zero price, cost, stock, avg stock
-- id, name, size, productType, category, price, costPrice, stock, avgStockNeeded, updatedAt
INSERT INTO products (id, name, size, productType, category, price, costPrice, stock, avgStockNeeded, updatedAt)
VALUES
('prod-001', 'Bhojanpatr', '15 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-002', 'Bhojanpatr', '14 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-003', 'Bhojanpatr', 'Kappeche', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-004', 'Bhojanpatr', 'Kappeche', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-005', 'Steel Glass', 'Regular', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-006', 'Steel Tamba', 'Regular', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-007', 'Steel Wati', 'Umiya / Chowdhury / Titan', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-008', 'Steel Dish', '6.5 No - Kohinoor/Mayuri/Chowdhury/AM/Mayuri47', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-009', 'Trey', 'Square Regular', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-010', 'Steel Fulpatr', 'regular size', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-011', 'Steel Tope set', '10-15 No set', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-012', 'Steel Tope set', '16-18 No set', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-013', 'Alu Tope set', '10-14 No set', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-014', 'Alu Tope set', '15-18 No set', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-015', 'Alu Tope set', '26-28 No set', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-016', 'Steel Dabba', '10-14 No - Life Time', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-017', 'Steel Dabba', '15-18 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-018', 'Puran Jali', '10 No = SK', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-019', 'Puran Jali', '11 No = SK', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-020', 'Steel Cooker', '1 Ltr', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-021', 'Steel Cooker', '2 Ltr', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-022', 'Steel Cooker', '3 Ltr', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-023', 'Kadai Steel', 'small size', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-024', 'Kadai Steel', 'Mid Size', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-025', 'Kadai Steel', 'Big size', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-026', 'Kadai Aluminium', '2 No - Deepak', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-027', 'Kadai Aluminium', '4 No - Deepak', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-028', 'Kadai Aluminium', '8 No - Deepak', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-029', 'Kadai Aluminium', '6 No - Meera', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-030', 'Parat', 'Tokdar - 14 No - (Mid size)', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-031', 'Parat', 'Tokdar - 16 No - (Big size)', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-032', 'Parat', 'Binding - 14 No - (Mid size)', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-033', 'Parat', 'Binding  - 16 No - (Big size)', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-034', 'Kitli', '1 Ltr', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-035', 'Kitli', '2 Ltr - Urmi', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-036', 'Kitli', '3 Ltr - Universe', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-037', 'Bucket', 'Lahan', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-038', 'Bucket', '15 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-039', 'Bucket', '17 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-040', 'POT (Poli Dabba)', 'small size - Akash', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-041', 'POT (Poli Dabba)', 'Big size', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-042', 'Masala Dabba', 'Medium Size', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-043', 'Masala Dabba', 'Big size', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-044', 'Ghamela steel', '2.5 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-045', 'Ghamela steel', '2 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-046', 'Ghamela steel', '1.5 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-047', 'Ghamela Aluminium', '2.5 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-048', 'Ghamela Aluminium', '2 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-049', 'Ghamela Aluminium', '1.5 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-050', 'Ghatach patel Aluminium', '2.5 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-051', 'Ghatach patel Aluminium', '2 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-052', 'Ghatach patel Aluminium', '1.5 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-053', 'Alu Tawa', '12 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-054', 'Alu Tawa', '11 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-055', 'polpat latan', 'Regular', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-056', 'polpat latan', 'Regular', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-057', 'Steel Rack', '2*2', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-058', 'Soyra - Steel', 'Regular', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-059', 'Bhande Jali', 'Square', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-060', 'Bhande Jali', 'Circle', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-061', 'Chaha handel Steel Tope', 'Regular size set', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-062', 'Chaha handel Aluminium Toop', 'Regular size set', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-063', 'Pithachi Chalan', 'Bhari wali', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-064', 'Patel zakan set steel', '10-18 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-065', 'Patel zakan set alu', '10-18 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-066', 'Patel zakan set alu', '2.5 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-067', 'Patel zakan set alu', '2 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-068', 'Patel zakan set alu', '1.5 Payli', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-069', 'Lokhandi Tawa', '11 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-070', 'Lokhandi Tawa', '12 No', 'Regular', 'Regular', 0, 0, 0, 0, NOW()),
('prod-071', 'Steel Varan chamcha', 'Bhari madhla', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-072', 'Steel Bhatya', 'Bhari madhla', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-073', 'steel zarya', 'Bhari madhla', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-074', 'Steel Ultani', 'Bhari madhla', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-075', 'Kisni box', 'Regular', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-076', 'Kisni patti', 'Mothi wali', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-077', 'Chaha chalni', '2 No - double jali', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-078', 'Chaha chalni', '3 No - double jali', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-079', 'Chaha chalni', '4 No - double jali', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-080', 'Steel Sandas - pakkad pattern', 'Bhari madhla', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-081', 'Steel Sandas - Khekda pattern', 'Bhari madhla', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-082', 'Poha spoon set', 'Bhari madhla', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-083', 'Steel Vili', 'Bhari madhli', 'Chote item', 'Chote item', 0, 0, 0, 0, NOW()),
('prod-084', 'Panchpatri/Pawali', '14 - 18 No', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-085', 'Panchpatri/Pawali', '20 - 24 No', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-086', 'Alu Dabba', '19-24 No', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-087', 'Alu Dabba', '25-28 No', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-088', 'Steel Dabba', '19-24 No', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-089', 'Steel Dabba', '25-28 No', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-090', 'Idli Pot', '12 No', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-091', 'Idli Pot', '16 No', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-092', 'Idli Pot', '20 No', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-093', 'Appe patr', 'Regular', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-094', 'Appe patr', 'Regular', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-095', 'Steel Handa', 'Medium Size', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-096', 'Steel Handa', 'Big size - Nashik Ghat ( Laxmi)', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-097', 'Steel Kalshi', 'Regular size', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-098', 'Dinner set', 'Regular', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-099', 'Mix idli/dhokla/ multi kadai', 'Regular', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-100', 'POT (Poli Dabba)', 'Plastic', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-101', 'Dhokala Bhandi', 'Regular', 'Gift', 'Gift', 0, 0, 0, 0, NOW()),
('prod-102', 'Lighter', 'Bhari madhla', 'Retail customer', 'Retail customer', 0, 0, 0, 0, NOW()),
('prod-103', 'Thrums bottle', 'Bhari madhla', 'Retail customer', 'Retail customer', 0, 0, 0, 0, NOW()),
('prod-104', 'Mixture Bhande', 'Small', 'Retail customer', 'Retail customer', 0, 0, 0, 0, NOW()),
('prod-105', 'Mixture Bhande', 'Medium', 'Retail customer', 'Retail customer', 0, 0, 0, 0, NOW()),
('prod-106', 'Mixture Bhande', 'Big', 'Retail customer', 'Retail customer', 0, 0, 0, 0, NOW()),
('prod-107', 'Mixture Bhande', 'Big', 'Retail customer', 'Retail customer', 0, 0, 0, 0, NOW()),
('prod-108', 'Tiffin patti', 'Regular', 'Retail customer', 'Retail customer', 0, 0, 0, 0, NOW()),
('prod-109', 'Tiffin clip', 'Regular', 'Retail customer', 'Retail customer', 0, 0, 0, 0, NOW()),
('prod-110', 'Kadai', 'Regular set', 'Non Stick', 'Non Stick', 0, 0, 0, 0, NOW()),
('prod-111', 'Toop', 'Regular set', 'Non Stick', 'Non Stick', 0, 0, 0, 0, NOW()),
('prod-112', 'Tawa', '14 No/ 4 mm', 'Non Stick', 'Non Stick', 0, 0, 0, 0, NOW()),
('prod-113', 'Fry pan', 'Regular', 'Non Stick', 'Non Stick', 0, 0, 0, 0, NOW()),
('prod-114', 'Dosa Tawa', '14 No/ 4 mm', 'Non Stick', 'Non Stick', 0, 0, 0, 0, NOW()),
('prod-115', 'Samai', '12 No', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-116', 'Samai', 'Choti size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-117', 'Samai', 'Mothi size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-118', 'Puja thali 4 no', 'Regular', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-119', 'Tamba Glass', 'Regular - Bhari madhele', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-120', 'Pital Tope', '10*14 (Papa will take care the size)', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-121', 'Tamba Matka', '2 No', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-122', 'Tamba Matka', '3 No', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-123', 'Tamba Handa - Handi type', 'Regular', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-124', 'Tamba Kalshi - Handi type', 'Regular', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-125', 'Soyra Pital', 'Regular', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-126', 'Tamba Taat - Devach', '7 No', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-127', 'Tamba Taat - Devach', '9 No', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-128', 'Tamba Taat - Devach', '13 No', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-129', 'Tamba Taat - Devach', '14 No', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-130', 'Tamba Taat - Devach', '15 No', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-131', 'Tamba', '8 No', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-132', 'Tamba', '8 No - Bhari madhele', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-133', 'Tamba', '10 No - Bhari madhele', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-134', 'Tamba', '12 No - Bhari madhele', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-135', 'Ganpati', 'Small Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-136', 'Ganpati', 'Big Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-137', 'Rangnath', 'Small Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-138', 'Rangnath', 'Big Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-139', 'Annapura', 'Small Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-140', 'Annapura', 'Big Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-141', 'Pital Ghanti', 'Small size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-142', 'Pital Ghanti', 'mid size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-143', 'Pital Ghanti', 'Big Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-144', 'Tamba Glass', 'Regular size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-145', 'Ghaghal', 'Big Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-146', 'Ghaghal', 'Small Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-147', 'Jali Diwa', 'Small Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW()),
('prod-148', 'Kapur aarti', 'Big Size', 'Tamba pital', 'Tamba pital', 0, 0, 0, 0, NOW());
