import { Product, Sale, Expense, ProductType } from "./types";

export const sampleProducts: Product[] = [
  {
    id: "p-101",
    name: "Stainless Saucepan 2L",
    variant: "2L / Stainless",
    size: "2L",
    pattern: "Plain",
    productType: "Regular",
    design: "Saucepan",
    category: "Cookware",
    price: 1399,
    costPrice: 899,
    stock: 24,
    stockAlwaysNeeded: true,
    avgStockNeeded: 20,
    reorderStatus: "ok",
    notes: "Popular item",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-102",
    name: "Cast Iron Tawa",
    variant: "10-inch / Cast Iron",
    size: "10in",
    pattern: "Plain",
    productType: "Regular",
    design: "Tawa",
    category: "Cookware",
    price: 1699,
    costPrice: 999,
    stock: 18,
    stockAlwaysNeeded: true,
    avgStockNeeded: 15,
    reorderStatus: "low",
    notes: "Heavy demand on weekends",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-103",
    name: "Copper Bottle 1L",
    variant: "1L / Copper",
    size: "1L",
    pattern: "Hammered",
    productType: "Gift",
    design: "Bottle",
    category: "Hydration",
    price: 1199,
    costPrice: 699,
    stock: 40,
    stockAlwaysNeeded: false,
    avgStockNeeded: 30,
    reorderStatus: "ok",
    notes: "New stock arrived",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-104",
    name: "Steel Varan chamcha",
    variant: "Bhari madhla",
    size: "Bhari madhla",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 99,
    costPrice: 50,
    stock: 100,
    stockAlwaysNeeded: false,
    avgStockNeeded: 50,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-105",
    name: "Steel Bhatya",
    variant: "Bhari madhla",
    size: "Bhari madhla",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 89,
    costPrice: 45,
    stock: 100,
    stockAlwaysNeeded: false,
    avgStockNeeded: 50,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-106",
    name: "steel zarya",
    variant: "Bhari madhla",
    size: "Bhari madhla",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 79,
    costPrice: 40,
    stock: 100,
    stockAlwaysNeeded: false,
    avgStockNeeded: 50,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-107",
    name: "Steel Ultani",
    variant: "Bhari madhla",
    size: "Bhari madhla",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 89,
    costPrice: 45,
    stock: 100,
    stockAlwaysNeeded: false,
    avgStockNeeded: 50,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-108",
    name: "Kisni box",
    variant: "Regular",
    size: "Regular",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Storage",
    price: 129,
    costPrice: 65,
    stock: 80,
    stockAlwaysNeeded: false,
    avgStockNeeded: 40,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-109",
    name: "Kisni patti",
    variant: "Mothi wali",
    size: "Mothi wali",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 69,
    costPrice: 35,
    stock: 120,
    stockAlwaysNeeded: false,
    avgStockNeeded: 60,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-110",
    name: "Chaha chalni",
    variant: "2 No - double jali",
    size: "2 No - double jali",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 49,
    costPrice: 25,
    stock: 150,
    stockAlwaysNeeded: false,
    avgStockNeeded: 75,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-111",
    name: "Chaha chalni",
    variant: "3 No - double jali",
    size: "3 No - double jali",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 59,
    costPrice: 30,
    stock: 150,
    stockAlwaysNeeded: false,
    avgStockNeeded: 75,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-112",
    name: "Chaha chalni",
    variant: "4 No - double jali",
    size: "4 No - double jali",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 69,
    costPrice: 35,
    stock: 150,
    stockAlwaysNeeded: false,
    avgStockNeeded: 75,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-113",
    name: "Steel Sandas - pakkad pattern",
    variant: "Bhari madhla",
    size: "Bhari madhla",
    pattern: "pakkad pattern",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 109,
    costPrice: 55,
    stock: 90,
    stockAlwaysNeeded: false,
    avgStockNeeded: 45,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-114",
    name: "Steel Sandas - Khekda pattern",
    variant: "Bhari madhla",
    size: "Bhari madhla",
    pattern: "Khekda pattern",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 119,
    costPrice: 60,
    stock: 90,
    stockAlwaysNeeded: false,
    avgStockNeeded: 45,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-115",
    name: "Poha spoon set",
    variant: "Bhari madhla",
    size: "Bhari madhla",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 139,
    costPrice: 70,
    stock: 80,
    stockAlwaysNeeded: false,
    avgStockNeeded: 40,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-116",
    name: "Steel Vili",
    variant: "Bhari madhli",
    size: "Bhari madhli",
    pattern: "",
    productType: "Chote item",
    design: "",
    category: "Utensils",
    price: 79,
    costPrice: 40,
    stock: 100,
    stockAlwaysNeeded: false,
    avgStockNeeded: 50,
    reorderStatus: "ok",
    photoUrl: "/next.svg",
    updatedAt: new Date().toISOString(),
  },
];

export const sampleSales: Sale[] = [
  {
    id: "s-201",
    productId: "p-101",
    qty: 1,
    amount: 50000,
    paymentMethod: "cash",
    soldAt: new Date().toISOString(),
    note: "Sample cash sale",
    user: "Team",
  },
  {
    id: "s-202",
    productId: "p-102",
    qty: 1,
    amount: 100000,
    paymentMethod: "qr_code",
    soldAt: new Date().toISOString(),
    note: "Sample QR sale",
    user: "Team",
  },
];
export const sampleExpenses: Expense[] = [
  {
    id: "e-301",
    type: "salary",
    amount: 30000,
    paymentMethod: "cash",
    description: "Sample salary",
    date: new Date().toISOString().slice(0, 10),
  },
  {
    id: "e-302",
    type: "stock_purchase",
    amount: 50000,
    paymentMethod: "cash",
    description: "Sample stock purchase",
    date: new Date().toISOString().slice(0, 10),
  },
];
